language: node_js
node_js:
  - "14"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t gaowenzhao/h5-cloud-hospital:latest .
  - docker push gaowenzhao/h5-cloud-hospital:latest
